Accept unknown args as this make this module future proof against future unknown args
It seems that rerun 0.23 introduces new args for module which are not supported here

```bash
error: unrecognized arguments: --time_sequence log_tick=0 --time_duration_nanos log_time=1748347179402113908
```

This makes it possible to have the code at the very least resilient to new argument